<?php

declare(strict_types=1);

/**
 * Votepit — Docker config generator.
 *
 * Renders config/config.php from environment variables at container start
 * (see docker/entrypoint.sh). Only runs when config/config.php does not
 * exist yet, so a self-hoster can always drop in their own hand-edited
 * config/config.php (bind-mounted or baked into a custom image) instead —
 * this script never overwrites one.
 *
 * This is a Docker-only convenience layer: the shared-hosting path
 * (documentation/installation.md) keeps configuring config/config.php by
 * hand from config/config.example.php, unchanged. Every key here maps
 * 1:1 onto that file — see it for the meaning of each value.
 */

function env_str(string $name, string $default = ''): string
{
    $value = getenv($name);

    return $value === false ? $default : $value;
}

function env_int(string $name, int $default): int
{
    $value = getenv($name);

    return $value === false || $value === '' ? $default : (int) $value;
}

function env_bool(string $name, bool $default): bool
{
    $value = getenv($name);
    if ($value === false || $value === '') {
        return $default;
    }

    return in_array(strtolower($value), ['1', 'true', 'yes', 'on'], true);
}

/** @return list<string> */
function env_list(string $name): array
{
    $value = getenv($name);
    if ($value === false || trim($value) === '') {
        return [];
    }

    return array_values(array_filter(array_map('trim', explode(',', $value)), static fn (string $v): bool => $v !== ''));
}

$appKey            = env_str('VOTEPIT_APP_KEY');
$identityServerKey = env_str('VOTEPIT_IDENTITY_SERVER_KEY');

if ($appKey === '' || $identityServerKey === '') {
    fwrite(STDERR, "Votepit (docker): VOTEPIT_APP_KEY and VOTEPIT_IDENTITY_SERVER_KEY are required and must not be empty.\n");
    fwrite(STDERR, "Generate each with: php -r \"echo bin2hex(random_bytes(32));\"\n");
    exit(1);
}

$config = [
    'env'                   => env_str('VOTEPIT_ENV', 'prod'),
    'app_url'               => env_str('VOTEPIT_APP_URL', 'http://localhost:8080'),
    'app_key'               => $appKey,
    'identity_server_key'   => $identityServerKey,
    'magic_link_ttl'        => env_int('VOTEPIT_MAGIC_LINK_TTL', 60 * 15),
    'db'                    => [
        'host'    => env_str('VOTEPIT_DB_HOST', 'db'),
        'port'    => env_int('VOTEPIT_DB_PORT', 3306),
        'name'    => env_str('VOTEPIT_DB_NAME', 'votepit'),
        'user'    => env_str('VOTEPIT_DB_USER', 'votepit'),
        'pass'    => env_str('VOTEPIT_DB_PASS'),
        'charset' => 'utf8mb4',
    ],
    'smtp'                  => [
        'host'       => env_str('VOTEPIT_SMTP_HOST'),
        'port'       => env_int('VOTEPIT_SMTP_PORT', 587),
        'user'       => env_str('VOTEPIT_SMTP_USER'),
        'pass'       => env_str('VOTEPIT_SMTP_PASS'),
        'encryption' => env_str('VOTEPIT_SMTP_ENCRYPTION', 'tls'),
        'from_email' => env_str('VOTEPIT_SMTP_FROM_EMAIL', 'noreply@example.com'),
        'from_name'  => env_str('VOTEPIT_SMTP_FROM_NAME', 'Votepit'),
    ],
    'admin_emails'          => env_list('VOTEPIT_ADMIN_EMAILS'),
    'session_lifetime'      => env_int('VOTEPIT_SESSION_LIFETIME', 60 * 60 * 24 * 30),
    // Docker self-host is always a single-account installation, same as
    // classic shared hosting — never overridable via env (cloud path
    // routing is a private, non-Community layer, see core/README.md).
    'routing_mode'          => 'self-host',
    'trust_cloudflare_ip'   => env_bool('VOTEPIT_TRUST_CLOUDFLARE_IP', false),
    'sentry_dsn'            => env_str('VOTEPIT_SENTRY_DSN'),
    'sentry_dsn_frontend'   => env_str('VOTEPIT_SENTRY_DSN_FRONTEND'),
    'matomo_url'            => env_str('VOTEPIT_MATOMO_URL'),
    'matomo_site_id'        => env_str('VOTEPIT_MATOMO_SITE_ID'),
    'session_cookie_domain' => env_str('VOTEPIT_SESSION_COOKIE_DOMAIN'),
    // Rate limits and extensions stay at Config::fromArray()'s built-in
    // defaults (same ones documented in config/config.example.php) — not
    // exposed as env vars, edit config/config.php by hand (bind-mounted)
    // if you need to change them.
    'rate_limits'           => [],
    'extensions'            => [],
];

$php = "<?php\n\ndeclare(strict_types=1);\n\n"
    . "// Generated by docker/generate-config.php from environment variables at\n"
    . "// container start (see docker/entrypoint.sh). Delete this file and mount\n"
    . "// your own config/config.php to take over configuration by hand instead —\n"
    . "// this script never overwrites an existing one.\n\n"
    . 'return ' . var_export($config, true) . ";\n";

echo $php;
